blank_issues_enabled: false
contact_links:
  - name: General Inquiry
    url: https://koodoreader.com/en/support
    about: Have questions or need help using Koodo Reader.
  - name: 问题咨询
    url: https://koodoreader.com/zh/support
    about: 有疑问或需要帮助
  - name: Report Issue
    url: https://koodoreader.com/en/support
    about: Encountered a bug or technical problem
  - name: 报告问题
    url: https://koodoreader.com/zh/support
    about: 遇到错误或技术问题
  - name: Feature Request
    url: https://koodoreader.com/en/support
    about: Have an idea for a new feature or improvement
  - name: 功能建议
    url: https://koodoreader.com/zh/support
    about: 希望添加新功能或觉得需要改进
