version: '1.0'
name: fetch
displayName: fetch
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - main
  schedule:
    - cron: '* 0 */2 * * ? *'
variables:
  global:
    - GITHUB_TOKEN
stages:
  - name: fetchurl
    displayName: fetchurl
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: fetchurl
        displayName: fetchurl
        nodeVersion: 21.5.0
        commands:
          - git clone https://${GITHUB_TOKEN}@github.com/cloudplains/migu_live202509.git
          - cd migu_live202509
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 执行编译命令 '
          - '# npm install && node fetchURLByWasm.js'
          - '# npm install && node fetchURLByAndroid.js'
          - '# npm install && node fetchURLByAndroidV2.js'
          - npm install && node fetchURLByAndroid720p.js
          - '# npm install && node fetchURLByWasmV2.js'
          - git config user.name "GitHub Actions"
          - git config user.email "actions@github.com"
          - git add .
          - '# GitHub Actions提交 '
          - git diff --quiet && git diff --staged --quiet || git commit -m "Update by GitHub Actions"
          - git push https://${GITHUB_TOKEN}@github.com/cloudplains/migu_live202509.git main:main
        strategy:
          retry: '0'
          timeout: 2